# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test_fasthtml',
                'doc_host': 'https://Jhutty.github.io',
                'git_url': 'https://github.com/Jhutty/test_fasthtml',
                'lib_path': 'test_fasthtml'},
  'syms': {'test_fasthtml.core': {'test_fasthtml.core.foo': ('core.html#foo', 'test_fasthtml/core.py')}}}
