# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['app', 'home']

# %% ../nbs/00_core.ipynb 3
from fasthtml.common import *
from fasthtml import FastHTML

# %% ../nbs/00_core.ipynb 6
app = FastHTML()

@app.get("/")
def home():
    return Div(H1('Hello World'), P('Some text'), P('Some more text'))
